KioskAdmin/src/main/java/com/morph/kiosk/controller/PortalBusinessController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.morph.kiosk.controller;

import com.morph.kiosk.persistence.entity.Business;
import com.morph.kiosk.persistence.entity.Kiosk;
import com.morph.kiosk.persistence.entity.KioskUser;
import com.morph.kiosk.persistence.service.PortalPersistence;
import com.morph.kiosk.persistence.service.UserPersistence;
import com.morph.kiosk.util.JsfUtil;
import com.morph.util.ProjectConstants;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.annotation.Resource;

/**
 *
 * @author Tobi-Morph-PC
 */
@Named(value = "portalBusinessController")
@SessionScoped
public class PortalBusinessController extends BaseController implements Serializable {

    @Resource(lookup = "java:global/KioskEJBModule-1.2/UserPersistence!com.morph.kiosk.persistence.service.UserPersistence")
    private UserPersistence userPersistence;

    @Resource(lookup = "java:global/KioskEJBModule-1.2/PortalPersistence!com.morph.kiosk.persistence.service.PortalPersistence")
    private PortalPersistence portalPersistence;
    
    private KioskUser user;
    private Business business = new Business();
    
    
    public PortalBusinessController() {
    }

    @Override
    void initUser(KioskUser user) {
        this.user = user;
    }

    public String viewDetail(Business business){
        this.business = business;
        return "sysBusinessDetail";
    }
    
    public void reset(){
        this.business = new Business();
    }
    
    public String emptyBusinessListRedirect() {
        if (null == this.business) {
            return "sysBusinesses";
        } else {
            return null;
        }
    }
    public void disableBusiness() {
        try {
            this.business.setModifiedDate(new Date());
            this.business.setStatus(false);
            portalPersistence.update(this.business);
            JsfUtil.addInfoFacesMessage(ProjectConstants.BUSINESS_DISABLED);
        } catch (Exception e) {
            JsfUtil.addErrorFacesMessage(ProjectConstants.UPDATE_UNSUCCESSFUL);
            e.getLocalizedMessage();
        }
    }

    public void enableBusiness() {
        try {
            this.business.setModifiedDate(new Date());
            this.business.setStatus(true);
            portalPersistence.update(this.business);
            JsfUtil.addInfoFacesMessage(ProjectConstants.BUSINESS_ENABLED);
        } catch (Exception e) {
            JsfUtil.addErrorFacesMessage(ProjectConstants.UPDATE_UNSUCCESSFUL);
            e.getLocalizedMessage();
        }
    }
    
    public void updateBusiness() {
        try {
            this.business.setModifiedDate(new Date());
            portalPersistence.update(this.business);
            JsfUtil.addInfoFacesMessage(ProjectConstants.UPDATE_SUCCESSFUL);
        } catch (Exception e) {
            JsfUtil.addErrorFacesMessage(ProjectConstants.UPDATE_UNSUCCESSFUL);
            e.getLocalizedMessage();
        }
    }


    public List<Business> getActiveBusinesses() {
        return portalPersistence.geAllActiveBusiness();
    }

    public List<Business> getDisabledBusinesses() {
        return portalPersistence.geAllDeacctiveBusiness();
    }
    
    public List<Kiosk> getBusinessActiveKiosks(){
        if(null != this.business){
            final List<Kiosk> l = portalPersistence.getActiveKioskByBusiness(this.business.getId());
            return l;
        }else{
            return Collections.EMPTY_LIST;
        }
    }
    
    
    public List<Kiosk> getBusinessDeativatedKiosks(){
        return portalPersistence.getDisabledKioskByBusiness(this.business.getId());
    }
    
    public KioskUser getUser() {
        return user;
    }

    public void setUser(KioskUser user) {
        this.user = user;
    }

    public Business getBusiness() {
        return business;
    }

    public void setBusiness(Business business) {
        this.business = business;
    }
    
}

KioskAdmin/src/main/webapp/business/businesses.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <ui:composition template="./../WEB-INF/template/portaluser.xhtml">

            <f:metadata>
                <f:event type="preRenderView" listener="#{portalBusinessController.reset()}"/>
            </f:metadata>
            
            <ui:define name="title">
                Portal Request
            </ui:define>

            <ui:define name="page-title">
                Business Requests
            </ui:define>

            <ui:define name="content">
                <h:form enctype="multipart/form-data">
                    <div class="col-lg-9 col-md-12">
                        <p:tabView dynamic="true" cache="true">
                            <p:tab title="Active Businesses">
                                <h:dataTable value="#{portalBusinessController.activeBusinesses}" var="biz" class="table table-striped table-bordered">
                                    <h:column>
                                        <f:facet name="header">Business Name </f:facet>
                                        <h:commandLink action="#{portalBusinessController.viewDetail(biz)}" value="#{biz.name}" class="text-info"></h:commandLink>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header"> Date Created </f:facet>
                                            #{biz.createdDate}
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">Active</f:facet>
                                            #{biz.status}
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">Business Owner</f:facet>
                                            #{biz.owner.firstName}
                                    </h:column>

                                </h:dataTable>
                            </p:tab>
                            <p:tab title="Disabled Businesses">
                                <h:dataTable value="#{portalBusinessController.disabledBusinesses}" var="biz" class="table table-hover table-bordered">
                                    <h:column>
                                        <f:facet name="header">Business Name </f:facet>
                                        <h:commandLink action="#{portalBusinessController.viewDetail(biz)}" value="#{biz.name}" class="text-info"></h:commandLink>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">Date Created</f:facet>
                                            #{biz.createdDate}
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">Active Status</f:facet>
                                            #{biz.status}
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">Business Owner</f:facet>
                                            #{biz.owner.firstName}
                                    </h:column>
                                </h:dataTable>
                            </p:tab>

                        </p:tabView>
                    </div>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

KioskAdmin/src/main/webapp/business/detail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:o="http://omnifaces.org/ui">

    <body>

        <ui:composition template="./../WEB-INF/template/portaluser.xhtml">

            <ui:define name="title">
                Portal Request
            </ui:define>

            <ui:define name="page-title">
                Business Requests
            </ui:define>

            <ui:define name="content">
                <o:form includeRequestParams="true" includeViewParams="true">

                    <div class="col-md-5">
                        <h:messages />
                        <div class="panel panel-default">
                            <div class="panel-heading"> Business </div>
                            <div class="panel-body">

                                <ui:include src="snippet/business_info.xhtml" />

                            </div>
                            <div class="panel-footer">
                                <div class="btn-group-xs">
                                    <h:commandLink action="sysBusinesses" value="Back to List" class="btn btn-secondary btn-sm" />
                                </div>
                            </div>
                        </div>
                    </div>
                </o:form>
            </ui:define>

        </ui:composition>

    </body>
</html>